### ISSUE TITLE
"Error: Not Found" while executing the action

### ISSUE THREAD

**Issue by marcusvoss** [ActionsDesk/github-actions-allow-list-as-code-action#7]
### Describe the bug

After configuring the action to be used in the simplest possible workflow I receive the following error:

```
Run ActionsDesk/github-actions-allow-list-as-code-action@v1.0.1
  with:
    token: ***
    enterprise: <org-slug>
    allow_list_path: github-actions-allow-list.yml
Error: Not Found
```

### To Reproduce

1. Setup a new private repo in an github organization
2. Restrict actions usage on org level (https://github.com/organizations/<org-slug>/settings/actions) to "Allow selected action"
3. Add "actionsdesk/github-actions-allow-list-as-code-action@v1.0.1" to the list of allowed actions
4. Add a new workflow like this 
```
name: Deploy GitHub Actions allow list

on:
  push:
    branches: [main]
    paths: [github-actions-allow-list.yml]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Deploy GitHub Actions allow list
        uses: actionsdesk/github-actions-allow-list-as-code-action@v1.0.1
        with:
          token: ${{ secrets.ENTERPRISE_ADMIN_TOKEN }}
          enterprise: <org-slug>
          # same as defined under `on.pull_requests.paths`
          allow_list_path: github-actions-allow-list.yml
```
5. create file "github-actions-allow-list.yml" in the root DIR of that repo with the following content
actions:
          - <span class="pl-s">actionsdesk/github-actions-allow-list-as-code-action@v1.0.1</span>
6. Trigger the workflow

### Expected behavior

1. As promised by the description of the action I would like to see that the org setting for the "Allow seleted action" do have the entry from the file
2. The workflow execution ends without an error

### Additional context

- @stoe  has access to my example repo
- please contact me, if you need any further information or testing
