### ISSUE TITLE
Support `docker://*`

### ISSUE THREAD

**Issue by stoe** [ActionsDesk/github-actions-allow-list-as-code-action#83]
### Is your feature request related to a problem? Please describe.

When using

```yml
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: docker://ghcr.io/OWNER/IMAGE_NAME
```

or 

```yml
jobs:
  my_first_job:
    steps:
      - name: My first step
        uses: docker://gcr.io/cloud-builders/gradle
```

the actions fails with `object null is not iterable (cannot read property Symbol(Symbol.iterator))`

### Describe the solution you'd like

Add support for `docker://`, e.g. `docker://alpine:3.8`

- https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-docker-hub-action
- https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-docker-public-registry-action

### Describe alternatives you've considered

Silently ignore `docker://`.

### Additional context

n/a
